// <auto-generated />
namespace Music_Artist_Hub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BackedUpOnName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BackedUpOnName));
        
        string IMigrationMetadata.Id
        {
            get { return "201803052249552_BackedUpOnName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
