// <auto-generated />
namespace Music_Artist_Hub.Migrations
{
  using System.CodeDom.Compiler;
  using System.Data.Entity.Migrations.Infrastructure;
  using System.Resources;

  [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreateGigTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateGigTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803041549274_CreateGigTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
